### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by neich** [ragingwind/mca-starter-kit#2]
Hi,

I've just followed the instructions and it seems to be a problem with sass. I got this error in the build step:

```
[13:49:45] Using gulpfile ~/mobile-chrome-apps-starter-kit/gulpfile.js
[13:49:45] Starting 'jshint'...
[13:49:45] Finished 'jshint' after 229 ms
[13:49:45] Starting 'build'...
[13:49:45] Starting 'styles'...
[13:49:45] Starting 'images'...
[13:49:46] Starting 'common'...
[13:49:46] Finished 'common' after 293 ms
[13:49:46] Finished 'build' after 1.31 s
{ [Error: spawn sass ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn sass',
  path: 'sass',
  name: 'Error',
  message: 'spawn sass ENOENT',
  stack: 'Error: spawn sass ENOENT\n    at exports._errnoException (util.js:746:11)\n    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)\n    at child_process.js:1144:20\n    at process._tickCallback (node.js:355:11)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-ruby-sass' }
[13:49:47] Finished 'styles' after 2.46 s
[13:49:47] Finished 'images' after 2.24 s
[13:49:47] Starting 'copy'...
[13:49:47] Starting 'bower'...
[13:49:48] Finished 'copy' after 133 ms
[13:49:48] 'bower' all files 0 B
[13:49:48] Finished 'bower' after 85 ms
[13:49:48] Starting 'manifest'...
[13:49:48] Finished 'manifest' after 185 ms
[13:49:48] Starting 'html'...
[13:49:48] Finished 'html' after 335 ms
[13:49:48] Starting 'vulcanize'...
[13:49:48] Starting 'vulcanize:copy'...
[13:49:48] Finished 'vulcanize:copy' after 5.51 ms
[13:49:48] Starting 'vulcanize:app'...

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT, no such file or directory '/home/me/mobile-chrome-apps-starter-kit/dist/elements/yo-list/yo-list.scss.css'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at readFile (/home/me/mobile-chrome-apps-starter-kit/node_modules/gulp-vulcanize/node_modules/vulcanize/lib/vulcan.js:62:20)
    at Object.<anonymous> (/home/me/mobile-chrome-apps-starter-kit/node_modules/gulp-vulcanize/node_modules/vulcanize/lib/vulcan.js:82:81)
    at exports.each (/home/me/mobile-chrome-apps-starter-kit/node_modules/gulp-vulcanize/node_modules/vulcanize/node_modules/whacko/lib/api/traversing.js:294:24)
    at inlineSheets (/home/me/mobile-chrome-apps-starter-kit/node_modules/gulp-vulcanize/node_modules/vulcanize/lib/vulcan.js:68:42)
    at concat (/home/me/mobile-chrome-apps-starter-kit/node_modules/gulp-vulcanize/node_modules/vulcanize/lib/vulcan.js:123:5)
    at Object.<anonymous> (/home/me/mobile-chrome-apps-starter-kit/node_modules/gulp-vulcanize/node_modules/vulcanize/lib/vulcan.js:142:16)
    at exports.each (/home/me/mobile-chrome-apps-starter-kit/node_modules/gulp-vulcanize/node_modules/vulcanize/node_modules/whacko/lib/api/traversing.js:294:24)
    at processImports (/home/me/mobile-chrome-apps-starter-kit/node_modules/gulp-vulcanize/node_modules/vulcanize/lib/vulcan.js:132:35)
    at Object.handleMainDocument [as processDocument] (/home/me/mobile-chrome-apps-starter-kit/node_modules/gulp-vulcanize/node_modules/vulcanize/lib/vulcan.js:277:3)
    at DestroyableTransform._transform (/home/me/mobile-chrome-apps-starter-kit/node_modules/gulp-vulcanize/index.js:44:14)
    at DestroyableTransform.Transform._read (/home/me/mobile-chrome-apps-starter-kit/node_modules/gulp-vulcanize/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/home/me/mobile-chrome-apps-starter-kit/node_modules/gulp-vulcanize/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/home/me/mobile-chrome-apps-starter-kit/node_modules/gulp-vulcanize/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
```

I've realized that bower just jumped to version 1.4, maybe there is a connection. 

Any hints? Thanks

**Comment by ragingwind** [comment]
Logs exactly presents what was wrong with you. sass spawning is failed. check your environments to find out whether you can use sass.
