### ISSUE TITLE
Error at runtime can't find ".cordaova/config.json"

### ISSUE THREAD

**Issue by mandaman2k** [ragingwind/mca-starter-kit#3]
After fowlling the instruction and installing gem + sass i could finally build the app. When I try to run it i get this:

[mandaman2k@UX32VD mobile-chrome-apps-starter-kit-0.1.0]$ gulp clean
[22:35:56] Using gulpfile ~/Polymer/mobile-chrome-apps-starter-kit-0.1.0/gulpfile.js
[22:35:56] Starting 'clean'...
[22:35:56] Finished 'clean' after 132 ms
[mandaman2k@UX32VD mobile-chrome-apps-starter-kit-0.1.0]$ gulp build --dist
[22:36:04] Using gulpfile ~/Polymer/mobile-chrome-apps-starter-kit-0.1.0/gulpfile.js
[22:36:04] Starting 'jshint'...
[22:36:04] Finished 'jshint' after 320 ms
[22:36:04] Starting 'build'...
[22:36:04] Starting 'styles'...
[22:36:05] Starting 'images'...
[22:36:06] Starting 'common'...
[22:36:06] Finished 'common' after 446 ms
[22:36:06] Finished 'build' after 2.2 s
[22:36:08] gulp-ruby-sass: directory elements/app-main
      write elements/app-main/app-main.scss.css
      write elements/app-main/app-main.scss.css.map
  directory elements/yo-greeting
      write elements/yo-greeting/yo-greeting.scss.css
      write elements/yo-greeting/yo-greeting.scss.css.map
  directory elements/yo-list
      write elements/yo-list/yo-list.scss.css
      write elements/yo-list/yo-list.scss.css.map
  directory styles
      write styles/main.scss.css
      write styles/main.scss.css.map
[22:36:08] Finished 'styles' after 3.62 s
[22:36:08] Finished 'images' after 3.56 s
[22:36:08] Starting 'copy'...
[22:36:08] Starting 'bower'...
[22:36:08] Finished 'copy' after 261 ms
[22:36:08] 'bower' all files 146.02 kB
[22:36:08] Finished 'bower' after 223 ms
[22:36:08] Starting 'manifest'...
[22:36:09] Finished 'manifest' after 271 ms
[22:36:09] Starting 'html'...
[22:36:09] Finished 'html' after 610 ms
[22:36:09] Starting 'vulcanize'...
[22:36:09] Starting 'vulcanize:copy'...
[22:36:09] Finished 'vulcanize:copy' after 17 ms
[22:36:09] Starting 'vulcanize:app'...
[22:36:10] Finished 'vulcanize:app' after 657 ms
[22:36:10] Finished 'vulcanize' after 676 ms
[mandaman2k@UX32VD mobile-chrome-apps-starter-kit-0.1.0]$ gulp run --dist
[22:36:17] Using gulpfile ~/Polymer/mobile-chrome-apps-starter-kit-0.1.0/gulpfile.js
[22:36:17] Starting 'run'...
[22:36:17] Finished 'run' after 1.9 ms

module.js:340
    throw err;
          ^
Error: Cannot find module '/home/mandaman2k/Polymer/mobile-chrome-apps-starter-kit-0.1.0/platform/.cordova/config.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /home/mandaman2k/Polymer/mobile-chrome-apps-starter-kit-0.1.0/node_modules/cca-delegate/node_modules/cordova-linkto/index.js:18:20
    at Object.oncomplete (fs.js:108:15)

Thank you

**Comment by ragingwind** [comment]
According to log message. cordova project is not exist. did you run `node ./configure com.your.company.YourAppName --android --ios` script after download?

**Comment by mandaman2k** [comment]
Yes, I followed the instructions I only removed iOS since I'm in Linux.

Thank you

—

**Comment by ragingwind** [comment]
great

**Comment by mandaman2k** [comment]
Hi, 

I still have the problem with the cordova config, i was just stating that i followed the instruction, but just removed ios, but i still cant get the app to run.

**Comment by ragingwind** [comment]
log please.

**Comment by mandaman2k** [comment]
Here it is, hope it helps

http://pastebin.com/g9GvLyj5

**Comment by ragingwind** [comment]
I confirm what is a problem thanks I will look for it

**Comment by ragingwind** [comment]
Install new version cca-delegate to solve it. `npm install --save cca-delegate` It should be work, config.json is deprecated in cca 6.0. I have to update it in next version. Sadly I started adding new features to master branch

**Comment by mandaman2k** [comment]
Hi, 

Thanks for the support, the last command you sent did the trick, it now builds without an error.

Now when I do 'gulp run --dist' i don't get the pop up window with the app like in the video.

**Comment by ragingwind** [comment]
You make sure that you have install bower packages or build app. did you learn those command? refer to https://github.com/ragingwind/mobile-chrome-apps-starter-kit#setup , check your dist folder. If you face another problem please make an issue

```
bower install
gulp clean && gulp build --dist && gulp run --dist
```
